/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCam_DisplayWbNull_H_
#define _chains_vipSingleCam_DisplayWbNull_H_

#include <include/link_api/system.h>
#include <include/link_api/sgxFrmcpyLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/nullLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    SgxFrmcpyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_M4LinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;
       UInt32    Capture_dsswbLinkID;
       UInt32    NullLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       SgxFrmcpyLink_CreateParams              SgxFrmcpyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_M4Prm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
       CaptureLink_CreateParams                Capture_dsswbPrm;
       NullLink_CreateParams                   NullPrm;
} chains_vipSingleCam_DisplayWbNullObj;

Void chains_vipSingleCam_DisplayWbNull_SetLinkId(chains_vipSingleCam_DisplayWbNullObj *pObj);

Void chains_vipSingleCam_DisplayWbNull_ResetLinkPrms(chains_vipSingleCam_DisplayWbNullObj *pObj);

Void chains_vipSingleCam_DisplayWbNull_SetPrms(chains_vipSingleCam_DisplayWbNullObj *pObj);

Void chains_vipSingleCam_DisplayWbNull_ConnectLinks(chains_vipSingleCam_DisplayWbNullObj *pObj);

Int32 chains_vipSingleCam_DisplayWbNull_Create(chains_vipSingleCam_DisplayWbNullObj *pObj, Void *appObj);

Int32 chains_vipSingleCam_DisplayWbNull_Start(chains_vipSingleCam_DisplayWbNullObj *pObj);

Int32 chains_vipSingleCam_DisplayWbNull_Stop(chains_vipSingleCam_DisplayWbNullObj *pObj);

Int32 chains_vipSingleCam_DisplayWbNull_Delete(chains_vipSingleCam_DisplayWbNullObj *pObj);

Void chains_vipSingleCam_DisplayWbNull_printBufferStatistics(chains_vipSingleCam_DisplayWbNullObj *pObj);

Void chains_vipSingleCam_DisplayWbNull_printStatistics(chains_vipSingleCam_DisplayWbNullObj *pObj);

Void chains_vipSingleCam_DisplayWbNull_SetAppPrms(chains_vipSingleCam_DisplayWbNullObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCam_DisplayWbNull_H_ */
